sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql5.sqlpub.com    # 远程地址
    port: 3310                 # 远程端口
    database: yjm123           # 远程数据库名
    username: jym123           # 远程用户名
    password: jkIo2ATbfkekoXeW # 远程密码